import type { Metadata } from "next"
import { MusicPlayerProvider } from '@/context/MusicPlayerContext'

import Header from '@/components/Header'
import MusicPlayer from '@/components/MusicPlayer'
import Footer from '@/components/Footer'

import '../styles/global.scss'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <MusicPlayerProvider>
          {/* <Header /> */}
          {children}
          <Footer />
          <MusicPlayer />
        </MusicPlayerProvider>
      </body>
    </html>
  )
}
